<?php

/*
 * Created by tpay.com
 */
use tpayLibs\src\_class_tpay\Utilities\Lang;
?>
<link rel="stylesheet" type="text/css" href="<?php echo $data['static_files_url'] ?>dac/_css/confirmation.css"/>

<div id="tpay-dac-confirmation">
    <div class="tpay-row tpay-header"><?php Lang::l('transfer_details') ?></div>
    <div class="tpay-row">
        <div class="col-l">
            <?php Lang::l('merchant_info') ?>:
        </div>
        <div class="col-r">
            <?php echo $data['merchant_data'] ?>
        </div>
    </div>
    <div class="tpay-row">
        <div class="col-l">
            <?php Lang::l('payment_amount') ?>:
        </div>
        <div class="col-r">
            <?php echo $data['transaction']['amount'] ?>
        </div>
    </div>
    <div class="tpay-row">
        <div class="col-l">
            <?php Lang::l('disposable_account') ?>:
        </div>
        <div class="col-r">
            <?php echo $data['transaction']['account_number'] ?>
        </div>
    </div>
</div>
