<?php

/*
 * Created by tpay.com
 */
const AMOUNT = 'amount';
?>
<link rel="stylesheet" type="text/css" href="<?php echo $data['static_files_url'] ?>View/Styles/confirmation.css"/>

<div id="tpay-szkwal-confirmation">
    <div class="tpay-row">
        <?php $lang->l('payment_method') ?>:
    </div>
    <div class="tpay-row">
        <select id="tpay-bank-select">
            <?php foreach ($data['banks'] as $b) { ?>
                <option value="<?php echo $b['account_number'] ?>"><?php echo $b['fullname'] ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="tpay-row">
        <div class="col-l"><?php $lang->l('merchant_info') ?></div>
        <div class="col-r"><?php echo $data['merchant_data'] ?></div>
    </div>
    <div class="tpay-row">
        <div class="col-l"><?php $lang->l('account_number') ?></div>
        <div id="tpay-bank-account" class="col-r"></div>
    </div>
    <div class="tpay-row">
        <div class="col-l"><?php $lang->l('payment_title') ?></div>
        <div class="col-r client-title"><?php echo $data['title'] ?></div>
    </div>
    <?php if ($data[AMOUNT] !== false) { ?>
        <div class="tpay-row">
            <div class="col-l"><?php $lang->l(AMOUNT) ?></div>
            <div class="col-r"><?php echo $data[AMOUNT]
                ?>
            </div>
        </div>
        <?php
    }
    ?>
    <div>
        <?php $lang->l('szkwal_info') ?>
    </div>
</div>

<script type="text/javascript" src="<?php echo $data['static_files_url'] ?>View/JS/confirmation.js"></script>
