<?php

/*
 * Created by tpay.com
 */
?>
<link rel="stylesheet" type="text/css" href="<?php echo $data['static_files_url'] ?>View/Styles/confirmation.css"/>

<div id="tpay-dac-confirmation">
    <div class="tpay-row tpay-header"><?php $lang->l('transfer_details') ?></div>
    <div class="tpay-row">
        <div class="col-l">
            <?php $lang->l('merchant_info') ?>:
        </div>
        <div class="col-r">
            <?php echo $data['merchant_data'] ?>
        </div>
    </div>
    <div class="tpay-row">
        <div class="col-l">
            <?php $lang->l('payment_amount') ?>:
        </div>
        <div class="col-r">
            <?php echo $data['transaction']['amount'] ?>
        </div>
    </div>
    <div class="tpay-row">
        <div class="col-l">
            <?php $lang->l('payment_title') ?>:
        </div>
        <div class="col-r">
            <?php echo $data['transaction']['title'] ?>
        </div>
    </div>
    <div class="tpay-row">
        <div class="col-l">
            <?php $lang->l('disposable_account') ?>:
        </div>
        <div class="col-r">
            <?php echo $data['transaction']['account_number'] ?>
        </div>
    </div>
</div>
