<?php

/*
 * Created by tpay.com
 */

?>
<script type="text/javascript">
    function redirect() {
        document.getElementById('tpay-payment').submit();
    }
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $data['static_files_url'] ?>View/Styles/style.css"/>
<body <?php if ($data['redirect']) { echo 'onload="redirect()"'; } ?>>
<form id="tpay-payment" class="tpay-form" action="<?php echo $data['action_url'] ?>" method="POST"
      accept-charset="UTF-8">
    <?php foreach ($data['fields'] as $name => $value) { ?>
        <input <?php if ($name === 'group') {
            echo ' id="tpay-channel-input" ';
        }
        if ($name === 'accept_tos') {
            echo ' id="tpay-regulations-input" ';
        } ?> type="hidden"
             name="<?php echo $name ?>"
             value="<?php echo $value ?>">
        <?php
    }
    ?>
    <input class="button" style="width: 500px ; height:50px"
           id="tpay-payment-submit" type="submit" value="<?php $lang->l('pay') ?>">
</form>
</body>
