<link rel="stylesheet" type="text/css" href="<?php echo $data['static_files_url'] ?>View/Styles/style.css"/>

<?php if (!empty($data['userCards'])) { ?>
    <form method="post" id="saved_card_payment_form" name="saved_card_payment_form" action="<?php echo $data['payment_redirect_path'] ?>">
        <div id="saved_card_payment" style="visibility: visible">
            <?php
            foreach ($data['userCards'] as $card) { ?>
                <input type="radio" name="savedId" id="cardN<?php echo $card['cardId'] ?>"
                       value="<?php echo $card['cardId'] ?>"/>
                <label for="cardN<?php echo $card['cardId'] ?>"><?php $lang->l('saved_card_label');
                    echo $card['shortCode']; if (isset($card['vendor'])) {?><img id="saved_icon" class="<?php echo $card['vendor'] ?>"/></label><?php } ?>
                <br/>
            <?php } ?>
            <input type="radio" name="savedId" id="newCard" value="new"><label
                for="newCard"> <?php $lang->l('new_card_label'); ?></label>
        </div>
    </form>
    <div id="card_form" style="display: none">
        <?php echo $data['new_card_form']; ?>
    </div>
<?php } else {
    echo $data['new_card_form'];
} ?>
<button id="card_continue_btn"><?php $lang->l('card_payment') ?>&nbsp;</button>
