<?php

/*
 * Created by tpay.com
 */

?>

<style>
    <?php include_once dirname(__FILE__) . '/../_css/style.css'; ?>
</style>
<div class="insidebg" id="main-payment">
    <img src="https://tpay.com/img/logo/tpaycom.png" height="145" width="250"/>
    <div id="kanaly_v">
        <div class="separator"><span><p class="font"><br/><?php tpay\Lang::l('cards_and_transfers') ?></p></span></div>
        <center>
            <div id="bank-selection-form"></div>
            <div class="separator"><span><p class="font"><br/><?php tpay\Lang::l('other_methods') ?></p></span></div>
            <div id="bank-selection-form2"></div>
            <br/>

            <?php echo $data['form'] ?>
        </center>

        <div class="regulations" style="padding-top: 20px; margin-bottom: 20px">
            <?php if ($data['show_regulations_checkbox'] === true) { ?>
                <p>
                    <input id="tpay-accept-regulations-checkbox" type="checkbox" name="regulations" value="0">

                    <?php tpay\Lang::l('accept') ?> <a href="<?php echo $data['regulation_url'] ?>"
                                                       target="_blank"><?php tpay\Lang::l('regulations_url') ?></a>
                    <?php tpay\Lang::l('regulations'); ?>
                </p>

            <?php } ?>
        </div>
    </div>
</div>

<script>
    var s = document.createElement('script'),
        regulation_checkbox = document.getElementById('tpay-accept-regulations-checkbox'),
        submit_form_input = document.getElementById('tpay-payment-submit'),
        regulations_form_input = document.getElementById('tpay-regulations-input'),
        bank_selection_form = document.getElementById('bank-selection-form'),
        bank_selection_form2 = document.getElementById('bank-selection-form2'),
        changeBank = function (bank_id) {
            var input = document.getElementById('tpay-channel-input'),
                bank_block = document.getElementById('bank-' + bank_id),
                active_bank_blocks = document.getElementsByClassName('bank-active'),
                class_name = 'bank-active', cn;

            input.value = bank_id;

            if (active_bank_blocks.length > 0) {
                cn = active_bank_blocks[0].className;
                cn = cn.replace(new RegExp("\\s?\\b" + class_name + "\\b", "g"), '');
                active_bank_blocks[0].className = cn;
            }

            if (bank_block !== null) {
                bank_block.className = bank_block.className + ' bank-active';
            }
        };
    s.src = 'https://secure.tpay.com/channels-<?php echo $data['merchant_id'] ?>1.js';
    s.onload = function () {
        var str = '', first = true, i, str2 = '', temp;
        var others = [29, 31, 49, 50, 57, 58, 59];

        for (i in tr_channels) {
            var channel = tr_channels[i],
                id = channel[0],
                width_style = (channel[0] == 40) ? 'width:270px' : '',
                checked, class_name;

            if (first) {
                checked = ' checked';
                class_name = ' bank-active';
                first = false;
                changeBank(id);
            } else {
                checked = '';
                class_name = ''
            }
            temp = '<div class="bank-block' + class_name + '" id="bank-' + id +
                '" style="background-image:url(' + channel[3] + ');' + width_style +
                '"><label onclick="changeBank(' + id + ')"><input type="radio" name="bank-select" value="' +
                id + '" ' + checked + ' style="visibility: hidden" /></label></div>';

            if (inArray(id, others) === false) {
                str += temp;
            } else {
                str2 += temp;
            }
        }
        bank_selection_form.innerHTML = str;
        bank_selection_form2.innerHTML = str2;
    };

    function inArray(needle, haystack) {
        var length = haystack.length;
        for (var i = 0; i < length; i++) {
            if (haystack[i] == needle) return true;
        }
        return false;
    }

    document.getElementsByTagName('head')[0].appendChild(s);

    <?php if ($data['show_regulations_checkbox'] === true){ ?>

    submit_form_input.onclick = function () {
        if (regulations_form_input.value == 0) {
            alert('<?php tpay\Lang::l('acceptance_is_required') ?>');
            return false;
        }
        return true;
    };

    regulation_checkbox.onchange = function () {
        regulations_form_input.value = (this.checked) ? 1 : 0;
    };

    <?php } ?>

</script>
